{"name": "test_post_activity_with_invalid_data", "status": "passed", "description": "\n            Test case: 004\n            Verify successful error message with adding of a new activity with invalid data\n        ", "attachments": [{"name": "log", "source": "d324c0a6-f451-4326-a52e-2e1539cd0dc6-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "75fcbdf9-f77a-4a48-80c7-e91408b1973a-attachment.txt", "type": "text/plain"}], "start": 1721908850747, "stop": 1721908851267, "uuid": "ba146e66-e66c-41d2-b3a4-be2177e53d26", "historyId": "04dd347945189056d3be9d7fe922f37a", "testCaseId": "04dd347945189056d3be9d7fe922f37a", "fullName": "test.api.test_fake_rest_api_activities.TestFakeRestAPIActivities#test_post_activity_with_invalid_data", "labels": [{"name": "parentSuite", "value": "test.api"}, {"name": "suite", "value": "test_fake_rest_api_activities"}, {"name": "subSuite", "value": "TestFakeRestAPIActivities"}, {"name": "host", "value": "DESKTOP"}, {"name": "thread", "value": "5908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.api.test_fake_rest_api_activities"}]}