{"name": "test_post_activity_with_invalid_data", "status": "passed", "description": "\n            Test case: 004\n            Verify successful error message with adding of a new activity with invalid data\n        ", "attachments": [{"name": "log", "source": "c1bb1d29-f660-4e48-b9ee-a60e7685b7c1-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "2d9dfc87-b757-4d0d-999e-c2a1b952d8b7-attachment.txt", "type": "text/plain"}], "start": 1721909931733, "stop": 1721909932229, "uuid": "47810132-9371-407c-ad3e-9899369308a5", "historyId": "04dd347945189056d3be9d7fe922f37a", "testCaseId": "04dd347945189056d3be9d7fe922f37a", "fullName": "test.api.test_fake_rest_api_activities.TestFakeRestAPIActivities#test_post_activity_with_invalid_data", "labels": [{"name": "parentSuite", "value": "test.api"}, {"name": "suite", "value": "test_fake_rest_api_activities"}, {"name": "subSuite", "value": "TestFakeRestAPIActivities"}, {"name": "host", "value": "DESKTOP"}, {"name": "thread", "value": "8072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.api.test_fake_rest_api_activities"}]}