[32mINFO    [0m fake_rest_api.log:activities.py:51 {'type': 'https://tools.ietf.org/html/rfc7231#section-6.5.1', 'title': 'One or more validation errors occurred.', 'status': 400, 'traceId': '00-67666ed0ddbd9641b290507c690990dd-93b7e1e218d6614d-00', 'errors': {'$.id': ['The JSON value could not be converted to System.Int32. Path: $.id | LineNumber: 0 | BytePositionInLine: 17.']}}