{"name": "test_post_activity_with_invalid_data", "status": "passed", "description": "\n            Test case: 004\n            Verify successful error message with adding of a new activity with invalid data\n        ", "attachments": [{"name": "log", "source": "29642814-2d67-4d75-8af8-8f8e86cde1c9-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "8025b201-2f7f-4569-a31a-b6d1984ea2e1-attachment.txt", "type": "text/plain"}], "start": 1721901957789, "stop": 1721901958253, "uuid": "6cb46d47-792d-479d-8045-d3a9e4e88a07", "historyId": "04dd347945189056d3be9d7fe922f37a", "testCaseId": "04dd347945189056d3be9d7fe922f37a", "fullName": "test.api.test_fake_rest_api_activities.TestFakeRestAPIActivities#test_post_activity_with_invalid_data", "labels": [{"name": "parentSuite", "value": "test.api"}, {"name": "suite", "value": "test_fake_rest_api_activities"}, {"name": "subSuite", "value": "TestFakeRestAPIActivities"}, {"name": "host", "value": "DESKTOP"}, {"name": "thread", "value": "13220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.api.test_fake_rest_api_activities"}]}