{"name": "test_post_activity_with_invalid_data", "status": "passed", "description": "\n            Test case: 004\n            Verify successful error message with adding of a new activity with invalid data\n        ", "attachments": [{"name": "log", "source": "3578360f-1b04-472e-82a4-9562b3fcaa32-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "f37b6808-fda3-401b-b123-ef6b98662e99-attachment.txt", "type": "text/plain"}], "start": 1721913895730, "stop": 1721913896190, "uuid": "52ebbd1b-d36f-44cf-8629-d426188b7f0d", "historyId": "04dd347945189056d3be9d7fe922f37a", "testCaseId": "04dd347945189056d3be9d7fe922f37a", "fullName": "test.api.test_fake_rest_api_activities.TestFakeRestAPIActivities#test_post_activity_with_invalid_data", "labels": [{"name": "parentSuite", "value": "test.api"}, {"name": "suite", "value": "test_fake_rest_api_activities"}, {"name": "subSuite", "value": "TestFakeRestAPIActivities"}, {"name": "host", "value": "DESKTOP"}, {"name": "thread", "value": "9252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.api.test_fake_rest_api_activities"}]}